language: node_js
node_js:
    - '0.10'

env:
  global:
    secure: "ecVAPtm1YNT4USYEbG5lnLnQ9pBWSDKHdjhUbQSk35UvunixLOvU/oeHzWqTIoDxEFKf0HehSXW9tM569bsBZth9O7WBwJAhSNkUrPVF4WDT1p+zsuakSZuZTAEVCqbeL+pPdVR968ML1UKP0hLgTbgDvM9HpyM4YQxVAOXfskI="

addons:
    sauce_connect: true

before_install:
    - openssl aes-256-cbc -K $encrypted_b7a3a86a6284_key -iv $encrypted_b7a3a86a6284_iv
        -in id_ci_github.enc -out ~/.ssh/id_ci_github -d

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphicsmagick
    - cd ..
    - git clone https://github.com/ZoetropeImaging/regression-tests.git
    - cd regression-tests
    - git clone --depth=50 --branch=$TRAVIS_BRANCH git://github.com/ZoetropeImaging/zoetrope-jquery.git
    - cd zoetrope-jquery
    - git checkout -qf $TRAVIS_COMMIT
    - cd ..

before_script:
    - npm install
    - cd zoetrope-jquery
    - npm install
    - gulp fetch
    - gulp
    - cd ..
    - http-server -p 8888 zoetrope-jquery/dist &
    - sleep 3

script:
    - cd tests
    - protractor testSuite.conf.js

after_success:
    - if [[$TRAVIS_BRANCH == 'v3']]; then ../travis_deploy_zoetrope.sh; fi

after_failure:
    - chmod 600 ~/.ssh/id_ci_github
    - ssh -i ~/.ssh/id_ci_github -o "StrictHostKeyChecking no" $TEST_IMAGES_SERVER -p2223 'mkdir' $TRAVIS_COMMIT
    - scp -i ~/.ssh/id_ci_github -P2223 -rp /tmp/screen* $TEST_IMAGES_SERVER:~/$TRAVIS_COMMIT 

notifications:
    slack:
        secure: Z0vtEJkHu7iDgSXMsVbsTmcn+N1GzBM6b2Ijx16DY2BCitt9h3tiSKUgazd3ULP6/9s/bKd0ZzkTIFTmsBszF7kh12uGrs2zB9GP20zoJiQ+e82toWkp9nV6Wx21f6bLiN+7ejiJqG3iV+2SUVyWvYchm4acu63kv1bVHxDuATI=

